name: 玳瑁猫-DBDemo
package: cloud.lazycat.app.democatdb
version: 0.0.7
description:
license: https://choosealicense.com/licenses/mit/
homepage:
author:
application:
  subdomain: democatdb
  workdir: /lzcapp/pkg/content /
  routes:
    - /=exec://3000,./lzcapp/pkg/content/run.sh
services:
  mysql:
    image: registry.lazycat.cloud/mysql
    binds:
      - /lzcapp/var/mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=LAZYCAT
      - MYSQL_DATABASE=LAZYCAT
      - MYSQL_USER=LAZYCAT
      - MYSQL_PASSWORD=LAZYCAT
envs:
  - name: DB_HOST
    value: mysql.${PACKAGE}.lzcapp
  - name: DB_PORT
    value: "3306"
  - name: DB_USER
    value: LAZYCAT
  - name: DB_PASSWORD
    value: LAZYCAT
  - name: DB_DATABASE
    value: LAZYCAT